USE Lecture12
GO

CREATE TABLE S(
FK1 INT,
FK2 INT,
A VARCHAR(100),
B VARCHAR(100),
C VARCHAR(100),
D VARCHAR(100),
E INT,
PRIMARY KEY(FK1,FK2)
)

INSERT INTO S VALUES(1, 1,' a1', 'b1', 'c1', 7, 2)
INSERT INTO S VALUES(1, 2, 'a_', 'b3', 'c1', 5, 2)
INSERT INTO S VALUES(1, 3, 'a2', 'b1', 'c2', Null, 2)
INSERT INTO S VALUES(2, 1, 'a3','b3', 'c2', Null, 100)
INSERT INTO S VALUES(2, 2, 'a3', 'b3', 'c3', Null, 100)

SELECT *
FROM S s1 LEFT JOIN S s2 ON s1.FK1 = s2.E

SELECT DISTINCT *
FROM S s1 INNER JOIN S s2 ON s1.FK1 = s2.E--10SELECT FK2, FK1, COUNT(DISTINCT B)
FROM S
GROUP BY FK2, FK1
HAVING FK1 = 0SELECT FK2, FK1, COUNT(C)
FROM S
GROUP BY FK2, FK1
HAVING MAX(E) < 0


--II

CREATE TABLE R(
RID INT PRIMARY KEY,
A INT,
B INT,
C INT,
D INT,
E INT,
F INT)

INSERT INTO R VALUES(1, 100, 200, 5, 200, 20, 11)
INSERT INTO R VALUES(2, 101, 50, 11, 200, 5, 12)
INSERT INTO R VALUES(3, 100, 100, 7, 200, 5, 13)
INSERT INTO R VALUES(4, 200, 200, 6, 200, 20, 14)
INSERT INTO R VALUES(5, 200, 100, 2, 200, 5, 9)
INSERT INTO R VALUES(6, 300, 50, 11, 200, 5, 10)

SELECT r1.RID, r1.A + r2.A C2, r1.A * r2.A C3
FROM R r1 LEFT JOIN R r2 ON r1.RID = r2.RID
WHERE r1.A > ANY (SELECT B
FROM R
WHERE C < 10)


--4
--1256

--5
SELECT R.*
FROM
(SELECT r1.RID, r2.A, r3.B
FROM R r1 INNER JOIN R r2 ON r1.A = r2.B
INNER JOIN R r3 ON r2.B > r3.D
WHERE r1.F > 10) t
RIGHT JOIN R ON t.RID = R.RID
----TRY
SELECT *
FROM S

SELECT * 
FROM R 

SELECT *
FROM S FULL OUTER JOIN R ON S.FK1=R.RID

SELECT *
FROM S CROSS JOIN R

SELECT *
FROM S

SELECT * 
FROM R 


SELECT S.RID,S.A
FROM
(SELECT *
FROM R
WHERE F<13)S
INNER JOIN
(SELECT *
FROM R)R
ON S.D=R.D


SELECT A,B,C
FROM (


)

SELECT A,B,C
FROM
(SELECT A,B,RID
FROM R
WHERE E=70)A
INNER JOIN
(SELECT C,RID
FROM R
WHERE E>5)B
ON A.RID=B.RID

SELECT FK1
FROM S

SELECT DISTINCT FK1
FROM S

SELECT A,B,C
FROM (
		SELECT A,b,Id
		FROM R
		WHERE m=70)t
INNER JOIN
(
		SELECT A,b,Id
		FROM R
		WHERE m=70)r
ON t.


SELECT S.RID,S.A
FROM
(SELECT *
FROM R
WHERE F<13)S
INNER JOIN
R
ON S.D=R.D


SELECT E,sum(no)
FROM
(SELECT FK1-FK2 as no,E
FROM S
)t
GROUP BY E


SELECT name
FROM (
	SELECT *
	FROM faculty_members
	INNER JOIN (SELECT faculty_id 
				From(
						(SELECT *
						FROM students
						WHERE name='sdsad'
						)students
				INNER JOIN schedule
				ON students.sgroup=schedule.shroup
				)A
				)B
	ON faculty_members.id=B.facultym_id
)C